require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses

Naming/MethodParameterName:
  MinNameLength: 1

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Lint/UselessSetterCall:
  Enabled: false
